"""update models

Revision ID: 0a5e20ffefb3
Revises: f3d74994c047
Create Date: 2025-09-19 22:34:21.659728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a5e20ffefb3'
down_revision = 'f3d74994c047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('layout_json', sa.JSON(), nullable=True))
        batch_op.drop_column('config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', mysql.JSON(), nullable=True))
        batch_op.drop_column('layout_json')
        batch_op.drop_column('background')

    # ### end Alembic commands ###
