"""update models

Revision ID: 0b1ff993082c
Revises: 62050e50ffcf
Create Date: 2025-09-20 11:30:02.857777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1ff993082c'
down_revision = '62050e50ffcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_scheme', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('widget_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('font_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('font_size', sa.String(length=20), nullable=True))
        batch_op.alter_column('layout_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', mysql.JSON(), nullable=True))
        batch_op.alter_column('layout_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.drop_column('font_size')
        batch_op.drop_column('font_family')
        batch_op.drop_column('widget_config')
        batch_op.drop_column('color_scheme')

    # ### end Alembic commands ###
