"""update models

Revision ID: 1c180c29b3d9
Revises: b3eab47fe21e
Create Date: 2025-09-15 10:39:39.090211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.mysql import JSON

# revision identifiers, used by Alembic.
revision = '1c180c29b3d9'
down_revision = 'b3eab47fe21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_data', JSON, nullable=True))
        batch_op.drop_column('references')
        batch_op.drop_column('experience')
        batch_op.drop_column('education_history')
        batch_op.drop_column('career_objective')
        batch_op.drop_column('skills')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('job_posting_ibfk_6'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'job_type', ['job_type_id'], ['id'])
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('job_posting_ibfk_6'), 'job_type', ['job_type'], ['id'])
        batch_op.drop_column('job_type_id')

    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('career_objective', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('education_history', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('experience', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('references', mysql.TEXT(), nullable=True))
        batch_op.drop_column('cv_data')

    # ### end Alembic commands ###
