"""update models

Revision ID: 497aa9023d69
Revises: e1ed862b4168
Create Date: 2025-09-19 22:28:38.058523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '497aa9023d69'
down_revision = 'e1ed862b4168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('template_type')
        batch_op.drop_column('fields_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields_config', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('template_type', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
