"""update models

Revision ID: 4f7fff25976e
Revises: 0b1ff993082c
Create Date: 2025-09-20 15:06:53.024637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f7fff25976e'
down_revision = '0b1ff993082c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_height', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('spacing', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sample_data', sa.Text(), nullable=True))
        batch_op.drop_column('widget_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_config', mysql.TEXT(), nullable=True))
        batch_op.drop_column('sample_data')
        batch_op.drop_column('spacing')
        batch_op.drop_column('line_height')

    # ### end Alembic commands ###
