"""update models

Revision ID: 51e2b8c3c1ef
Revises: 0a5e20ffefb3
Create Date: 2025-09-19 22:42:16.470063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e2b8c3c1ef'
down_revision = '0a5e20ffefb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
