"""update models

Revision ID: 62050e50ffcf
Revises: 51e2b8c3c1ef
Create Date: 2025-09-20 11:21:48.104499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62050e50ffcf'
down_revision = '51e2b8c3c1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###
