"""update models

Revision ID: 73bb3adda0f3
Revises: a7f3b5f7933b
Create Date: 2025-09-23 10:39:27.475715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bb3adda0f3'
down_revision = 'a7f3b5f7933b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_sections')
    # ### end Alembic commands ###
