"""empty message

Revision ID: 7910b40d4cbb
Revises: 
Create Date: 2025-09-19 14:00:57.359500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7910b40d4cbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('layout_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=mysql.ENUM('admin', 'candidate', 'approver', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('user_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('user_ibfk_1'), 'company', ['company_id'], ['id'])
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'candidate', 'approver', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    op.drop_table('templates')
    # ### end Alembic commands ###
