"""update models

Revision ID: 83b8c2be4bf9
Revises: cea56a8d0e54
Create Date: 2025-09-19 16:35:49.394136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83b8c2be4bf9'
down_revision = 'cea56a8d0e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_require')
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('requirements')

    op.create_table('job_require',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['job_posting.id'], name=op.f('job_require_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
