"""update models

Revision ID: 877876fcf400
Revises: 13db4f1421c7
Create Date: 2025-09-15 21:12:37.376381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877876fcf400'
down_revision = '13db4f1421c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
