"""init database

Revision ID: 9044e18f60d3
Revises: 
Create Date: 2025-09-23 22:35:47.624000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '9044e18f60d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrative_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('short_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=False),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('color_scheme', sa.Text(), nullable=True),
    sa.Column('widget_config', sa.Text(), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('font_size', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=200), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('design', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.Column('administrative_region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_region_id'], ['administrative_regions.id'], ),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('districts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('wards',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_tax_id', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.String(length=200), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('business_status', sa.Boolean(), nullable=True),
    sa.Column('phone_contact', sa.String(length=20), nullable=True),
    sa.Column('legal_representative', sa.String(length=100), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('ward_code', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ward_code'], ['wards.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_tax_id'),
    sa.UniqueConstraint('phone_contact'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('job_type_id', sa.Integer(), nullable=True),
    sa.Column('salary_range', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('ward_code', sa.String(length=20), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ward_code'], ['wards.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('job_application_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_application.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_application_id', 'post_id', name='uix_job_post')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('comment')
    op.drop_table('application')
    op.drop_table('job_posting')
    op.drop_table('company')
    op.drop_table('wards')
    op.drop_table('districts')
    op.drop_table('provinces')
    op.drop_table('job_application')
    op.drop_table('user')
    op.drop_table('templates')
    op.drop_table('job_type')
    op.drop_table('administrative_units')
    op.drop_table('administrative_regions')
    # ### end Alembic commands ###
