"""add related location

Revision ID: 9feb918f55d3
Revises: b05afc65a23b
Create Date: 2025-09-03 20:50:10.150707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9feb918f55d3'
down_revision = 'b05afc65a23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('district_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ward_code', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'wards', ['ward_code'], ['code'])
        batch_op.create_foreign_key(None, 'districts', ['district_code'], ['code'])
        batch_op.create_foreign_key(None, 'provinces', ['province_code'], ['code'])

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('district_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ward_code', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'provinces', ['province_code'], ['code'])
        batch_op.create_foreign_key(None, 'wards', ['ward_code'], ['code'])
        batch_op.create_foreign_key(None, 'districts', ['district_code'], ['code'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ward_code')
        batch_op.drop_column('district_code')
        batch_op.drop_column('province_code')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ward_code')
        batch_op.drop_column('district_code')
        batch_op.drop_column('province_code')

    # ### end Alembic commands ###
