"""update models

Revision ID: a5f0d02f7116
Revises: 73bb3adda0f3
Create Date: 2025-09-23 11:09:30.065246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5f0d02f7116'
down_revision = '73bb3adda0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_sections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_sections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('config', mysql.JSON(), nullable=True),
    sa.Column('position', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('template_sections_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
