"""update models

Revision ID: a7f3b5f7933b
Revises: 4f7fff25976e
Create Date: 2025-09-20 15:12:13.639700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7f3b5f7933b'
down_revision = '4f7fff25976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_config', sa.Text(), nullable=True))
        batch_op.drop_column('sample_data')
        batch_op.drop_column('spacing')
        batch_op.drop_column('line_height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_height', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('spacing', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('sample_data', mysql.TEXT(), nullable=True))
        batch_op.drop_column('widget_config')

    # ### end Alembic commands ###
