"""add administrative tables

Revision ID: b05afc65a23b
Revises: 
Create Date: 2025-09-03 20:42:41.119579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05afc65a23b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrative_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('short_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.Column('administrative_region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_region_id'], ['administrative_regions.id'], ),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('districts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('wards',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('district_code', sa.String(length=20), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wards')
    op.drop_table('districts')
    op.drop_table('provinces')
    op.drop_table('administrative_units')
    op.drop_table('administrative_regions')
    # ### end Alembic commands ###
