"""update models

Revision ID: b08e40caf9f3
Revises: 877876fcf400
Create Date: 2025-09-15 21:22:48.274036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b08e40caf9f3'
down_revision = '877876fcf400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('layout_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('background',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('profile')
        batch_op.drop_column('sections')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('profile', mysql.TEXT(), nullable=True))
        batch_op.alter_column('background',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('layout_json')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
