"""update models

Revision ID: b3eab47fe21e
Revises: 65d0bcb03123
Create Date: 2025-09-05 21:53:00.272268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3eab47fe21e'
down_revision = '65d0bcb03123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('job_type',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('type', sa.String(length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('type')
    # )
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.alter_column('job_type',
            existing_type=mysql.VARCHAR(length=50),   # hiện tại là varchar
            type_=sa.Integer(),                      # đổi thành integer
            existing_nullable=True)
        batch_op.create_foreign_key(None, 'job_type', ['job_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('job_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('job_type')
    # ### end Alembic commands ###
