"""init schema

Revision ID: d6cc7d786f51
Revises: 
Create Date: 2025-09-24 02:39:36.492375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6cc7d786f51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='application_status'),
               nullable=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('layout_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', mysql.JSON(), nullable=True))
        batch_op.alter_column('layout_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='application_status'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
