"""update models

Revision ID: e1ed862b4168
Revises: fee533da77cf
Create Date: 2025-09-19 22:15:47.675224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ed862b4168'
down_revision = 'fee533da77cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fields_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('fields_config')
        batch_op.drop_column('template_type')

    # ### end Alembic commands ###
