"""update models

Revision ID: f3d74994c047
Revises: 497aa9023d69
Create Date: 2025-09-19 22:29:48.526633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3d74994c047'
down_revision = '497aa9023d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
        batch_op.drop_column('background')
        batch_op.drop_column('layout_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_json', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('background', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('config')

    # ### end Alembic commands ###
