"""update models

Revision ID: fee533da77cf
Revises: b08e40caf9f3
Create Date: 2025-09-16 04:10:33.286672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fee533da77cf'
down_revision = 'b08e40caf9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=mysql.ENUM('admin', 'candidate', 'approver'),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'candidate', 'approver'),
               existing_nullable=True)

    # ### end Alembic commands ###
